github:
  prebuilds:
    master: true
    branches: true
    pullRequests: false
    pullRequestsFromForks: false
    addComment: false
    addBadge: false
    addLabel: false
tasks:
  - before: |
      export ANDROID_HOME=/home/gitpod/android-sdk;
      export FLUTTER_HOME=/home/gitpod/flutter;

      sudo apt-get update && \
          sudo apt-get -y install build-essential libkrb5-dev gcc make gradle openjdk-8-jdk && \
          sudo apt-get clean && \
          sudo apt-get -y autoremove && \
          sudo apt-get -y clean && \
          sudo rm -rf /var/lib/apt/lists/*;

      cd /home/gitpod && \
          git clone https://github.com/flutter/flutter.git -b stable /home/gitpod/flutter
      mkdir -p /home/gitpod/android-sdk && \
          cd /home/gitpod/android-sdk && \
          wget https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip && \
          unzip commandlinetools-linux-8092744_latest.zip && \
          rm -f commandlinetools-linux-8092744_latest.zip && \
          mv ~/android-sdk/cmdline-tools/ latest && \
          mkdir -p ~/android-sdk/cmdline-tools/ && \
          mv latest ~/android-sdk/cmdline-tools/

      mkdir -p /home/gitpod/.android
            touch /home/gitpod/.android/repositories.cfg
            export PATH="${FLUTTER_HOME}/bin:${ANDROID_HOME}/cmdline-tools/latest/bin:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/platform-tools-2:${ANDROID_HOME}/tools:$PATH"
            yes | sdkmanager "platform-tools" "platforms;android-29" "build-tools;29.0.3"
            export PATH="${FLUTTER_HOME}/bin:${ANDROID_HOME}/cmdline-tools/latest/bin:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/platform-tools-2:${ANDROID_HOME}/tools:$PATH"
vscode:
  extensions:
    - Dart-Code.flutter
