name: APK Release
on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.x'
          channel: 'stable'
      - name: configure release signing
        env:
          JKS_KEY: ${{ secrets.JKS_KEY }}
          STORE_PWD: ${{ secrets.STORE_PWD }}
          KEY_PWD: ${{ secrets.KEY_PWD }}
        run: |
          cat > upload-keystore.jks <<<$JKS_KEY; \
          echo "storeFile=$(pwd)/upload-keystore.jks" >> android/key.properties; \
          echo "keyAlias=upload" >> android/key.properties; \
          echo "storePassword=${{ secrets.STORE_PWD }}" >> android/key.properties; \
          echo "keyPassword=${{ secrets.KEY_PWD }}" >> android/key.properties; \
      - run: flutter pub get
      - run: flutter build apk --release
        # - run: flutter build appbundle --release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/apk/release/app-release.apk
