name: APK Release
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.x'
          channel: 'stable'
      - name: configure release signing
        env:
          JKS_KEY: ${{ secrets.JKS_KEY }}
          STORE_PWD: ${{ secrets.STORE_PWD }}
          KEY_PWD: ${{ secrets.KEY_PWD }}
        run: |
          cat > upload-keystore.jks <<<$JKS_KEY; \
          touch android/app/key.properties; \
          echo "storeFile=$(pwd)/upload-keystore.jks" >> android/app/key.properties; \
          echo "keyAlias=upload" >> android/app/key.properties; \
          echo "storePassword=${{ secrets.STORE_PWD }}" >> android/app/key.properties; \
          echo "keyPassword=${{ secrets.KEY_PWD }}" >> android/app/key.properties; \
          cat android/app/key.properties
      - run: flutter pub get
      - run: flutter build apk --release
      - run: flutter build appbundle --release
      - uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: 'build/**/*.apk'
          retention-days: 2
